### ISSUE TITLE
animation server: `'ServerGoalHandle' object has no attribute 'aborted'`

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_motion#382]
```
[animation_node-14] [ERROR] [1673863108.856204582] [animation.action_server]: Error raised in execute callback: 'ServerGoalHandle' object has no attribute 'aborted'
[animation_node-14] Traceback (most recent call last):
[animation_node-14]   File "/opt/ros/rolling/local/lib/python3.10/dist-packages/rclpy/action/server.py", line 325, in _execute_goal
[animation_node-14]     execute_result = await await_or_execute(execute_callback, goal_handle)
[animation_node-14]   File "/opt/ros/rolling/local/lib/python3.10/dist-packages/rclpy/executors.py", line 108, in await_or_execute
[animation_node-14]     return callback(*args)
[animation_node-14]   File "/colcon_ws/install/bitbots_animation_server/lib/python3.10/site-packages/bitbots_animation_server/animation_node.py", line 88, in execute_cb
[animation_node-14]     goal.aborted(text="HCM not controllable. Will now become controllable. Try again later.")
[animation_node-14] AttributeError: 'ServerGoalHandle' object has no attribute 'aborted'
```

**Comment by SammyRamone** [comment]
I think this is a ROS 2 issue. They changed how this is named. We needed to do the same thing für DynUp. It's something like abort() now
https://github.com/bit-bots/bitbots_motion/blob/4ad2e8320b75f47f88fa24e9e165ea860b6254a1/bitbots_dynup/src/dynup_node.cpp#L247-L251
